### ISSUE TITLE
Consider not using the term blacklist

### ISSUE THREAD

**Issue by PhilETaylor** [sqids/sqids-blocklist#1]
https://inclusivenaming.org/word-lists/tier-1/whitelist/

**Comment by 4kimov** [comment]
Sorry for late response - just now saw this (apparently I don't get notifications for issues/PRs).
This [has been adjusted already a while back](https://github.com/sqids/sqids-spec/commit/616cae1d0034cf20c75c9bc543ddd25d392243bc). Thanks for bringing to my attention 👍
